version: '2'

services:
  goldblum:
    build: ./server
    image: transitorykris/goldblum:latest
    ports:
      - "8001:8001"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: goldblum
    volumes:
      - /var/lib/mysql
